name = "gbict.nl"  # The name of your Cloudflare Workers project
type = "webpack"  # If you're using a build tool like webpack; adjust as necessary
account_id = "dcafc27d61574f2a87e05da9c8f9f783"  # Your Cloudflare account ID
workers_dev = true  # If you want to deploy to your workers.dev subdomain
zone_id = "07e624401ab473e443288683b9dea57f"
kv_namespaces = [
  { id = "MY_KV", binding="MY_KV" }
]

[build]
command = "npm run build"  # Your build command
upload = { format = "service-worker"  }

# You can also specify environment specific configurations
[env.production]
name = "GBICT-Website-production"
kv_namespaces = [
  { id = "MY_KV_PROD", binding="MY_KV" }
]
