name = "gbict-website"
type = "webpack"  # or "javascript", depending on your setup
account_id = "your_cloudflare_account_id"
workers_dev = true

[build]
command = "npm run build"
upload.format = "service-worker"

[build.upload]
main = "dist/server.js"  # Adjust this to point to the correct output file
bucket = "./build/client"  # The directory of your static assets
