name = "gbict-website"
type = "webpack"  # or "javascript", depending on your setup
account_id = "dcafc27d61574f2a87e05da9c8f9f783"
workers_dev = true

[build]
command = "npm run build"
upload = { format = "service-worker", main = "dist/server.js", bucket = "./build/client" }