name = "gbict-website"  # Corrected to a valid project name
workers_dev = true  # Enable development on workers.dev subdomain if desired

# Remove the zone_id if it's unnecessary, as noted by the deprecation warning
# zone_id = ""  # This line can be removed unless specifically required

kv_namespaces = [
  { id = "MY_KV", binding = "MY_KV" }
]

# Define your build commands if necessary
[build]
command = "npm run build"  # Your build command

# Example environment configurations (if necessary)
[env.production]
name = "gbitt-website-production"
kv_namespaces = [
  { id = "MY_KV_PROD", binding = "MY_KV" }
]
