- name: Cloudflare Pages GitHub Action
  uses: cloudflare/pages-action@v1.5.0
  with:
    # Cloudflare API Token
     apiToken: ${{QiEo3Y2gRpbE4E3X2Lnodhj5lLNCgqEA_LR9-_2E}}
 
     # Cloudflare Account ID
     accountId: 'dcafc27d61574f2a87e05da9c8f9f783'
     # The name of the Pages project to upload to
     projectName: GBICT
     # The directory of static assets to upload
     directory: 
     # GitHub Token
     gitHubToken: # optional
     # The name of the branch you want to deploy to
     branch: main # optional
     # The working directory in which to run Wrangler
   workingDirectory: # optional
   # The version of Wrangler to use
   wranglerVersion: 3 # optional, default is 2
         
