- name: Cloudflare Pages GitHub Action
  uses: cloudflare/pages-action@v1.5.0
  with:
    apiToken: ${{QiEo3Y2gRpbE4E3X2Lnodhj5lLNCgqEA_LR9-_2E}}
    accountId: 'dcafc27d61574f2a87e05da9c8f9f783'
    projectName: 'GBICT Website'
    directory: 'build'
    gitHubToken: 
    branch: 'main'  # Optional
    workingDirectory: ''  # Optional
    wranglerVersion: '3'  # Optional
