name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Use whatever Node version your project requires

    - name: Install dependencies
      run: npm install  # Or 'yarn install', if you use Yarn

    - name: Run Dev
      run: npm run   # Assumes you have a `lint` script in your package.json

    - name: Build
      run: npm run build  # Assumes you have a `build` script in your package.json

    - name: Check build artifacts
      run: ls -R build  # Adjust this to where your build artifacts are outputted

      env:
        CLOUDFLARE_API_TOKEN: ${{QiEo3Y2gRpbE4E3X2Lnodhj5lLNCgqEA_LR9-_2E}}
    - name: deploy
      run: npm run deploy  # Adjust this to where your build artifacts are outputted
