name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Ensure this matches your project requirement

      - name: Install dependencies
        run: npm install 
        
      - name: Install stream
        run: npm i stream 

      - name: Post-install script
        run: node ./scripts/draco.cjs

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 'dcafc27d61574f2a87e05da9c8f9f783'
          command: 'pages deploy ./build/client --project-name gbict-website'
